const CartTypes = {
    ADD_TO_CART: 'ADD_TO_CART',
    DECREASE_QTY: 'DECREASE_QTY',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
    CART_CLEAR_ALL_ITEMS: 'CART_CLEAR_ALL_ITEMS',
    CART_SHIPPING_ADDRESS: "CART_SHIPPING_ADDRESS",
    CART_PAYMENT_METHOD: "CART_PAYMENT_METHOD",
    LOADING_CURRENT_ITEM: 'LOADING_CURRENT_ITEM',
}
export default CartTypes